- name: This playbook will installs, configures and deploys web page in ngnix web server
  hosts: all
  vars:
   greeting_message: "DevOps"
   automation_tool: "Ansible"
   provisioner_tool: "Docker"
   proxy_conf:
    http_proxy: http://genproxy.corp.amdocs.com:8080
    https_proxy: https://genproxy.corp.amdocs.com:8080
  tasks:
  - name: install nginx in ubuntu
    apt: name=nginx state=latest update_cache=yes
    environment: "{{proxy_conf}}"
    when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
 
  - name: Create web root folder
    file: path=/var/html state=directory mode=0777

  - name: Configuration ngnix in ubuntu
    copy: src=default dest=/etc/nginx/sites-available/default
    when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )

  - name: Deploy  Our curtom web page
    template: src=index.html.j2 dest=/var/html/index.html

  - name: Restart nginx in Ubuntu
    command: "service nginx restart"
    when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
