apiVersion: v1
kind: Service
metadata:
 name: tomcat
 labels:
   run: tomcat
spec:
  type: NodePort
  ports:
  - nodePort: 29081
    port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: tomcat
