apiVersion: v1
kind: Service
metadata:
 name: my-tomcat
 labels:
   run: my-tomcat
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    run: my-tomcat
